modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="marrelics"
version="1.0.0"
displayName="MARRelics"
description="Addon for Blood Magic and Relics that adds a relic ring which absorbs damage using LP from the player network"
authors="Vladisss"

[[dependencies.marrelics]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.marrelics]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
